# Generated by Django 5.0.6 on 2026-07-26 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vod', '0004_movie_series_lang_genre_dates'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='movie',
            name='vod_movie_title_idx',
        ),
        migrations.RemoveIndex(
            model_name='series',
            name='vod_series_title_idx',
        ),
    ]
