# Generated by Django 6.0.6 on 2026-07-17 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, help_text="Nom d'icône (ex: tv, sports, news)", max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo_url', models.URLField(blank=True)),
                ('stream_url', models.TextField(help_text='URL HLS/M3U8 du flux')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('xtream_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('viewers_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, default='BF', max_length=50)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channels', to='channels.category')),
            ],
            options={
                'verbose_name': 'Chaîne',
                'verbose_name_plural': 'Chaînes',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EPG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epg_entries', to='channels.channel')),
            ],
            options={
                'verbose_name': 'Programme EPG',
                'verbose_name_plural': 'Programmes EPG',
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['channel', 'start_time'], name='channels_ep_channel_a72a89_idx')],
            },
        ),
    ]
