# Generated by Django 5.0.6 on 2026-07-26 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0005_channel_lang_genre_quality'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='channel',
            name='channels_channel_name_idx',
        ),
    ]
